<a href="https://colab.research.google.com/github/Nobel712/Visualisation-library/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

arrange

In [ ]:
import numpy as np
ar=np.arange(1,23)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [ ]:
ar=np.arange(1,13,2)
ar

array([ 1,  3,  5,  7,  9, 11])

linsapace

In [ ]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
ar=np.array([[11,23,45,67],
            [34,67,54,67],
            [34,54,34,53]])
ar

array([[11, 23, 45, 67],
       [34, 67, 54, 67],
       [34, 54, 34, 53]])

In [ ]:
ar.reshape(4,3)

array([[11, 23, 45],
       [67, 34, 67],
       [54, 67, 34],
       [54, 34, 53]])

ravel() # 2d array k 1d te niya ase

In [ ]:
ar.ravel()

array([11, 23, 45, 67, 34, 67, 54, 67, 34, 54, 34, 53])

flatten() #multidimentional array k  1d te niya asa

In [ ]:
ar.flatten()

array([11, 23, 45, 67, 34, 67, 54, 67, 34, 54, 34, 53])

transpose # 2d kore

In [ ]:
ar.transpose()

array([[11, 34, 34],
       [23, 67, 54],
       [45, 54, 34],
       [67, 67, 53]])

In [ ]:
ar=np.arange(1,101).reshape(10,10)
ar

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
ar.ndim

2

In [ ]:
ar.dtype

dtype('int64')

In [ ]:
ar[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ar[6:7,2:3]

array([[63]])

In [ ]:
ar[0: ,0:-1]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
ar[:-1,:-1]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [ ]:
ar[:,3:4]

array([[ 4],
       [14],
       [24],
       [34],
       [44],
       [54],
       [64],
       [74],
       [84],
       [94]])

In [ ]:
ar[8:9]

array([[81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [ ]:
ar[:,:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [ ]:
ar[4:7,2:6]

array([[43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

In [ ]:
ar.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
a=np.arange(1,61).reshape(10,6)

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [ ]:
b=np.arange(61,121).reshape(10,6)

In [ ]:
b

array([[ 61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78],
       [ 79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102],
       [103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119, 120]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[  1,   2,   3,   4,   5,   6,  61,  62,  63,  64,  65,  66],
       [  7,   8,   9,  10,  11,  12,  67,  68,  69,  70,  71,  72],
       [ 13,  14,  15,  16,  17,  18,  73,  74,  75,  76,  77,  78],
       [ 19,  20,  21,  22,  23,  24,  79,  80,  81,  82,  83,  84],
       [ 25,  26,  27,  28,  29,  30,  85,  86,  87,  88,  89,  90],
       [ 31,  32,  33,  34,  35,  36,  91,  92,  93,  94,  95,  96],
       [ 37,  38,  39,  40,  41,  42,  97,  98,  99, 100, 101, 102],
       [ 43,  44,  45,  46,  47,  48, 103, 104, 105, 106, 107, 108],
       [ 49,  50,  51,  52,  53,  54, 109, 110, 111, 112, 113, 114],
       [ 55,  56,  57,  58,  59,  60, 115, 116, 117, 118, 119, 120]])

vertical concatenate

In [ ]:
np.vstack((a,b))

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42],
       [ 43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78],
       [ 79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102],
       [103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119, 120]])

horizontal concatenate

In [ ]:
np.hstack((a,b))

array([[  1,   2,   3,   4,   5,   6,  61,  62,  63,  64,  65,  66],
       [  7,   8,   9,  10,  11,  12,  67,  68,  69,  70,  71,  72],
       [ 13,  14,  15,  16,  17,  18,  73,  74,  75,  76,  77,  78],
       [ 19,  20,  21,  22,  23,  24,  79,  80,  81,  82,  83,  84],
       [ 25,  26,  27,  28,  29,  30,  85,  86,  87,  88,  89,  90],
       [ 31,  32,  33,  34,  35,  36,  91,  92,  93,  94,  95,  96],
       [ 37,  38,  39,  40,  41,  42,  97,  98,  99, 100, 101, 102],
       [ 43,  44,  45,  46,  47,  48, 103, 104, 105, 106, 107, 108],
       [ 49,  50,  51,  52,  53,  54, 109, 110, 111, 112, 113, 114],
       [ 55,  56,  57,  58,  59,  60, 115, 116, 117, 118, 119, 120]])

In [ ]:
np.split(a,2,axis=1)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21],
        [25, 26, 27],
        [31, 32, 33],
        [37, 38, 39],
        [43, 44, 45],
        [49, 50, 51],
        [55, 56, 57]]), array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24],
        [28, 29, 30],
        [34, 35, 36],
        [40, 41, 42],
        [46, 47, 48],
        [52, 53, 54],
        [58, 59, 60]])]

In [ ]:
n='this is'
m=' boy'
np.char.add(n,m)

array('this is boy', dtype='<U11')

In [ ]:
np.char.upper(n)

array('THIS IS', dtype='<U7')

In [ ]:
n11=np.char.center(n,50,fillchar='*')
print(n11)
n12=np.char.center(n,48,fillchar='*')
print(n12)

*********************this is**********************
********************this is*********************


In [ ]:
s1='dym'
s2='ttt'
np.char.join([':',"/"],[s1,s2])

array(['d:y:m', 't/t/t'], dtype='<U5')

In [ ]:
ar=np.array([[[1,2,3],
              [1,3,6]],
             [[6,5,3],
             [4,6,9]]])
ar

array([[[1, 2, 3],
        [1, 3, 6]],

       [[6, 5, 3],
        [4, 6, 9]]])

In [ ]:
ar[:,:,1:2]

array([[[2],
        [3]],

       [[5],
        [6]]])

In [ ]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(ar,4)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random. rand(4,2)# +

array([[0.06976724, 0.38687359],
       [0.5561412 , 0.21985275],
       [0.41030696, 0.26419894],
       [0.4896887 , 0.44736244]])

In [ ]:
np.random.randn(4,2) #+,-

array([[-0.52775997, -1.53324294],
       [-0.61795267, -0.27976889],
       [-0.86036769,  0.75376979],
       [-0.48805496, -1.31449808]])

In [ ]:
np.random.randint(8,size=(4,6))

array([[6, 2, 6, 1, 6, 6],
       [7, 0, 4, 2, 3, 0],
       [1, 0, 6, 3, 2, 1],
       [0, 1, 2, 0, 5, 5]])

In [ ]:
np.random.randint(1,8,size=(4,6))

array([[1, 5, 6, 5, 2, 6],
       [6, 7, 6, 7, 6, 2],
       [1, 3, 6, 4, 5, 2],
       [6, 6, 1, 5, 2, 3]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
ar=np.array([[1,2,3]])
np.repeat(ar,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
a=np.array([1,2,3,4])
b=a.copy()
b[0]=100
print(a,b)

[1 2 3 4] [100   2   3   4]


In [ ]:
a=np.array([1,2,3,4])
b=a.view()
b[0]=100
print(a,b)

[100   2   3   4] [100   2   3   4]


In [ ]:
a=np.array([1,2,3,4])
b=a
b[0]=100
print(a,b)

[100   2   3   4] [100   2   3   4]


In [ ]:
data=np.genfromtxt('/content/yyy.txt',delimiter=',')
data.astype('int64')

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])